trigger:
- none

resources:
- repo: self

variables:
- group: "deployment-configuration"
- group: "tokens"

stages:
- stage: Add or remove deployment target
  displayName: Terraform
  jobs:  
  - job: run_bash
    displayName: Run bash
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - task: AzureCLI@2
      displayName: Azure CLI
      inputs:
        azureSubscription: arm-service-connection-rh-subcription-vse-950dkk
        scriptType: bash
        scriptPath: scripts/add_remove_deployment_target.sh
        scriptArguments: "$(action) deployment-configuration $(variable-name) $(resource-group) $(cluster-name) $(namespace) $(AZURE_DEVOPS_EXT_PAT)"
        addSpnToEnvironment: true
