trigger:
- none

resources:
- repo: self

variables:
- group: "terraform-backend"

stages:
- stage: terraform_destroy_traffic_manager_endpoint
  displayName: Terraform destroy Traffic Manager endpoint
  jobs:  
  - job: run_bash
    displayName: Run bash
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - task: AzureCLI@2
      displayName: Azure CLI
      inputs:
        azureSubscription: arm-service-connection-rh-subcription-vse-950dkk
        scriptType: bash
        scriptPath: terraform.sh
        scriptArguments: "--action=destroy --module=tme --backend-secret=$(AKSCOMM_TF_BACKEND_CLIENT_SECRET) --workspace=$(terraform-workspace)"
        addSpnToEnvironment: true
- stage: terraform_destroy_aks_cluster
  displayName: Terraform destroy AKS cluster
  jobs:  
  - job: run_bash
    displayName: Run bash
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - task: AzureCLI@2
      displayName: Azure CLI
      inputs:
        azureSubscription: arm-service-connection-rh-subcription-vse-950dkk
        scriptType: bash
        scriptPath: terraform.sh
        scriptArguments: "--action=destroy --module=aks --backend-secret=$(AKSCOMM_TF_BACKEND_CLIENT_SECRET) --workspace=$(terraform-workspace)"
        addSpnToEnvironment: true
