trigger:
- none

resources:
- repo: self

variables:
- group: "terraform-backend"

stages:
- stage: destroy
  displayName: Destroy core infrastructure
  jobs:  
  - job: destroy
    displayName: Destroy core infrastructure
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - task: AzureCLI@2
      displayName: Azure CLI
      inputs:
        azureSubscription: arm-service-connection-rh-subcription-vse-950dkk
        scriptType: bash
        scriptPath: destroy_core_infrastructure.sh
        scriptArguments: $(AKSCOMM_TF_BACKEND_CLIENT_SECRET)
        addSpnToEnvironment: true
