name: provision-core-infrastructure

trigger:
- none

resources:
- repo: self

variables:
- group: "terraform-backend"

stages:
- stage: provision
  displayName: Provision core infrastructure
  jobs:  
  - job: provision
    displayName: Provision core infrastructure
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - task: AzureCLI@2
      displayName: Azure CLI
      inputs:
        azureSubscription: $(arm-service-connection-rahummel-subscription-microsoft-internal)
        scriptType: bash
        scriptPath: provision_core_infrastructure.sh
        scriptArguments: $(AKSCOMM_TF_BACKEND_CLIENT_SECRET)
