trigger:
- none

resources:
- repo: self

variables:
- group: "terraform-backend"

stages:
- stage: destroy
  displayName: Destroy Traffic Manager endpoint
  jobs:  
  - job: destroy
    displayName: Destroy Traffic Manager endpoint
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - task: AzureCLI@2
      displayName: Azure CLI
      inputs:
        azureSubscription: arm-service-connection-rh-subcription-vse-950dkk
        scriptType: bash
        scriptPath: terraform.sh
        scriptArguments: "--action=destroy --module=tme --backend-secret=$(AKSCOMM_TF_BACKEND_CLIENT_SECRET) --workspace=$(terraform-workspace)"
        addSpnToEnvironment: true
