trigger:
- none

resources:
- repo: self

variables:
- group: "terraform-backend"

stages:
- stage: apply
  displayName: Apply RBAC identities
  jobs:  
  - job: apply
    displayName: Apply RBAC identities
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - task: AzureCLI@2
      displayName: Azure CLI
      inputs:
        azureSubscription: arm-service-connection-rh-subcription-vse-950dkk
        scriptType: bash
        scriptPath: terraform.sh
        scriptArguments: "--action=apply --module=rbac --backend-secret=$(AKSCOMM_TF_BACKEND_CLIENT_SECRET) --workspace=$(terraform-workspace)"
        addSpnToEnvironment: true
- stage: grant_admin_consent
  displayName: Grant admin consent
  jobs:  
  - deployment: grant_admin_consent
    displayName: Grant admin consent
    environment: aks-commander-global
