trigger:
- none

resources:
- repo: self

variables:
- group: "deployment-configuration"

stages:
- stage: terraform
  displayName: Terraform
  jobs:  
  - job: run_bash
    displayName: Run bash
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - task: AzureCLI@2
      displayName: Azure CLI
      inputs:
        azureSubscription: arm-service-connection-rh-subcription-vse-950dkk
        scriptType: bash
        scriptPath: scripts/variable_test.sh
        scriptArguments: "$(resource-group) $(cluster-name) $(namespace)"
        addSpnToEnvironment: true
