apiVersion: v1
kind: Service
metadata:
  name: health-service
  labels:
    app: health
    tier: frontend
spec:
  selector:
    app: health
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
  type: ClusterIP
